// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9XXZ7rOQy7e_zfXSipvkWQzuIOeMejg',
    appId: '1:717049204917:web:029fcc49e468e71796aefc',
    messagingSenderId: '717049204917',
    projectId: 'task-manager-9077e',
    authDomain: 'task-manager-9077e.firebaseapp.com',
    storageBucket: 'task-manager-9077e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwIa-6ymAbY5D05Myn9u2Qp_Lz4c3-L8',
    appId: '1:717049204917:android:636692ad27be408d96aefc',
    messagingSenderId: '717049204917',
    projectId: 'task-manager-9077e',
    storageBucket: 'task-manager-9077e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoTW-I_i_tP_hZ6oUjrexEUpiZPUCX_Y',
    appId: '1:717049204917:ios:2c5dd772a7d2c92996aefc',
    messagingSenderId: '717049204917',
    projectId: 'task-manager-9077e',
    storageBucket: 'task-manager-9077e.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoTW-I_i_tP_hZ6oUjrexEUpiZPUCX_Y',
    appId: '1:717049204917:ios:2c5dd772a7d2c92996aefc',
    messagingSenderId: '717049204917',
    projectId: 'task-manager-9077e',
    storageBucket: 'task-manager-9077e.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs9XXZ7rOQy7e_zfXSipvkWQzuIOeMejg',
    appId: '1:717049204917:web:184930515d07c8ef96aefc',
    messagingSenderId: '717049204917',
    projectId: 'task-manager-9077e',
    authDomain: 'task-manager-9077e.firebaseapp.com',
    storageBucket: 'task-manager-9077e.firebasestorage.app',
  );
}
